### PR TITLE
Build Caliper's cuda variant when cuda is enabled

### PR DESCRIPTION
**Pull request by joshessman-llnl**
Do we also want to enable any of caliper/RAJA/umpire by default on TOSS (as is currently the case on blueos)?

### CODE REVIEW

**Comment by jamiebramwell** [comment]
> 
> 
> Do we also want to enable any of caliper/RAJA/umpire by default on TOSS (as is currently the case on blueos)?

I believe the answer is yes (at least for RAJA/umpire), but I defer to @white238 .

**Comment by jamiebramwell** [comment]
Testing this on rzansel now.

**Comment by jamiebramwell** [comment]
I got this error when building `--spec=+cuda+raja+umpire+caliper`. Any idea what's going on?

```
+++WS1/bramwell/gitspaces/serac/uberenv_libs/clang-10.0.1/amgx-2.1.x/include  -I/usr/WS1/bramwell/gitspaces/serac/uberenv_libs/clang-10.0.1/zlib-1.2.11/include  -c fem/fespace.cpp -o fem/fespace.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
fem/../linalg/../general/backends.hpp(63): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during instantiation of "T AtomicAdd(T &, T) [with T=double]"
fem/restriction.cpp(1358): here

1 error detected in the compilation of "fem/restriction.cpp".
```

**Review by jonwong12 — APPROVED** [review]

**Comment by jamiebramwell** [comment]
Yep! Adding `cuda_arch=70` to the spec worked!

**Review by jamiebramwell — APPROVED** [review]

**Pull request merged**
