### PR TITLE
[DISCUSS] Enable warnings as errors

### PR DESCRIPTION
**Pull request by white238**
This could get annoying but we are in a very good state atm and I would hate to slide back into lots of warnings.  It can be turned off through `config-build.py -DENABLE_WARNINGS_AS_ERRORS=OFF`.

Alternatively we could turn it on just on the docker builds so it doesn't hinder people during development.

### CODE REVIEW

**Comment by jamiebramwell** [comment]
I think this encourages good practices, but I could be convinced of the docker-only solution if people have strong feelings.

**Review by jamiebramwell — APPROVED** [review]

**Review by joshessman-llnl — APPROVED** [review]

**Comment by white238** [comment]
I also turned on BLT's ENABLE_ALL_WARNINGS (basically "-Wall -Wextra" depending on the compiler).

**Comment by white238** [comment]
LGTM

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
Speak now or be required to quiet all warnings for compilation to succeed...

**Review by samuelpmishLLNL — APPROVED** [review]

**Pull request merged**
