### PR TITLE
disambiguate by_attr implementation

### LINKED ISSUE #1077: by_attr helper function won't compile
I noticed that the `by_attr` helper function provided to be used with `serac::Domain` won't compile. When I try to build an executable using it I get this error 
image

### PR DESCRIPTION
**Pull request by samuelpmishLLNL**
fixes https://github.com/LLNL/serac/issues/1077, adds more tests to verify

### CODE REVIEW

**Review by jamiebramwell — APPROVED** [review]
Thanks for the quick fix @samuelpmishLLNL !

**Comment by kswartz92** [comment]
When using a 3D mesh, would `ofBoundaryElements` work exactly like `ofFaces`? And in 2D would `ofBoundaryElements` work exactly as `ofEdges`?

**Comment by samuelpmishLLNL** [comment]
> When using a 3D mesh, would `ofBoundaryElements` work exactly like `ofFaces`? And in 2D would `ofBoundaryElements` work exactly as `ofEdges`?

They're not the same thing. For example, a 3D mesh has face elements on the interior and the boundary, but `ofBoundaryFaces` will not visit interior faces when evaluating the predicate.

**Comment by kswartz92** [comment]
> > When using a 3D mesh, would `ofBoundaryElements` work exactly like `ofFaces`? And in 2D would `ofBoundaryElements` work exactly as `ofEdges`?
> 
> They're not the same thing. For example, a 3D mesh has face elements on the interior and the boundary, but `ofBoundaryFaces` will not visit interior faces when evaluating the predicate.

Got it, thanks! Should we maybe add `ofBoundaryFaces` to the test? I primarily use `Domain` for boundary attributes. Unless it is tested somewhere else in the repo I didn't notice?

**Comment by samuelpmishLLNL** [comment]
maybe the `ofFaces` and `ofEdges` should be removed in favor of `ofInteriorFaces` and `ofBoundaryFaces`. I wonder, is there a real use-case where one would want to include boundary and interior faces in the same domain?

**Review by kswartz92 — APPROVED** [review]
thanks @samuelpmishLLNL !

**Comment by kswartz92** [comment]
> maybe the `ofFaces` and `ofEdges` should be removed in favor of `ofInteriorFaces` and `ofBoundaryFaces`. I wonder, is there a real use-case where one would want to include boundary and interior faces in the same domain?

I think it could be useful for solving physics on a partial domain. E.g. an interior material interface may become the domain boundary along with boundary faces.

**Pull request merged**
