### PR TITLE
Add option to select language/sidre path for Inlet

### PR DESCRIPTION
**Pull request by joshessman-llnl**
This change generalizes Serac's wrapper over Inlet to support input files other than the "primary" lua file.

### CODE REVIEW

**Review by jamiebramwell — APPROVED** [review]

**Comment by white238** [comment]
Can we turn this on for the serac driver?

**Review by white238 — APPROVED** [review]

**Comment by jamiebramwell** [comment]
> 
> 
> Can we turn this on for the serac driver?

I believe it is since we don't pass the language argument in the driver and it defaults to Lua.

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
> 
> 
> > Can we turn this on for the serac driver?
> 
> I believe it is since we don't pass the language argument in the driver and it defaults to Lua.

Wait, you were asking to turn this on instead of off. I need more ☕

**Pull request merged**
