### PR TITLE
Add mpi rank and size to the base solver class

### PR DESCRIPTION
**Pull request by jamiebramwell**
This adds some minor fixes that came out of my Tribol integration work. 

- Adds MPI rank and size data members to the base solver class for easy access
- Make style

### CODE REVIEW

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
LGTM

**Review by joshessman-llnl — APPROVED** [review]
Were the style changes just an application of the existing `.clang-format`?

**Comment by jamiebramwell** [comment]
Yep. I just ran `make style` on the repo. Yet another example of how we need a style checker (if not modifier) in our CI process.

**Comment by jamiebramwell** [comment]
Because I am lazy and will forget! 😄

**Comment by adrienbernede** [comment]
I insisted on having the distinction in MFEM, so this separation exist in their scripts between "check" and "apply". Maybe there is something reusable there.

However they don’t use git hooks. I already did something like that for a project. But I have other priorities at the moment.

**Review by white238 — APPROVED** [review]

**Comment by jamiebramwell** [comment]
LGTM

**Pull request merged**
