### PR TITLE
Convert CTest's XML file to JUnit

### PR DESCRIPTION
**Pull request by white238**
This should allow gitlab to recognize our unit tests.

### CODE REVIEW

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
well this is frustrating.  Gitlab artifacted the correct file but didn't create a report.  My guess is because there is no Gitlab MR to go along w/ this PR.  More investigation tomorrow.

**Comment by white238** [comment]
> well this is frustrating. Gitlab artifacted the correct file but didn't create a report. My guess is because there is no Gitlab MR to go along w/ this PR. More investigation tomorrow.

Nevermind! It worked! It was just buried in gitlab's UI!  You have to click on the Pipeline's number then on the "Tests" tab halfway down the page.

**Comment by white238** [comment]
LGTM

**Review by jamiebramwell — APPROVED** [review]

**Comment by white238** [comment]
LGTM

**Review by joshessman-llnl — APPROVED** [review]

**Pull request merged**
