### PR TITLE
Adapting to new naming of hostconfig file

### PR DESCRIPTION
**Pull request by adrienbernede**
Quick fix for CI.
Now fails in tests with the 3 toolchains (others branches opened to fix these).

### CODE REVIEW

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
FYI, I’m testing you branch with this bugfix [there](https://lc.llnl.gov/gitlab/bernede1/serac/pipelines/9380).

**Comment by adrienbernede** [comment]
Not failing for the right reason!
... Spack is driving me crazy...

**Comment by white238** [comment]
Thanks @adrienbernede

**Comment by adrienbernede** [comment]
Failure was apparently due to my configuration on LC (.spack). We will see how it holds in the future.

**Pull request merged**
