### PR TITLE
Remove global partitioning from our HYPRE builds

### PR DESCRIPTION
**Pull request by jamiebramwell**
This removes the global partitioning option that we had patched into the hypre spack package. This option is generally not scalable and it causes issues with creating Hypre matricies from block systems. The default install directory has also been added to the `.gitignore` file.

### CODE REVIEW

**Comment by jamiebramwell** [comment]
LGTM

**Review by joshessman-llnl — APPROVED** [review]

**Review by jandrej — APPROVED** [review]

**Comment by jamiebramwell** [comment]
For some reason, this is failing the gcc TPL install on quartz. 🤷

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
I believe the azure failure is due to a microsoft outage.

**Pull request merged**
