### PR TITLE
Add more artifacts

### PR DESCRIPTION
**Pull request by white238**

### CODE REVIEW

**Comment by white238** [comment]
LGTM

**Review by jamiebramwell — APPROVED** [review]

**Review by joshessman-llnl — APPROVED** [review]

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
I wonder if there is a way to stop github from using a different email everytime?

**Comment by white238** [comment]
> I wonder if there is a way to stop github from using a different email everytime?

Apparently it's not every time. so I'll just keep adding these as i see them.

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Pull request merged**
