### PR TITLE
Update the `StateManager` before saving

### LINKED ISSUE #729: Sidre not storing updated mesh information
When the mesh object is mutated by a `Solid` module, the sidre-based output file does not contain this updated mesh information.

### PR DESCRIPTION
**Pull request by jamiebramwell**
This is an alternate implementation of https://github.com/LLNL/serac/pull/802 that avoids saving the `FiniteElementState`s in the global `StateManager`. However, this comes at the additional cost of calling `updateState` and `updateDual` for each state you wish to save.

Resolves https://github.com/LLNL/serac/issues/729

### CODE REVIEW

**Review by white238 — APPROVED** [review]

**Comment by jamiebramwell** [comment]
I looked into adding quadrature data to this, and I think it's enough work it should be a separate PR.

**Comment by jamiebramwell** [comment]
Any other issues with this branch? @solberg2 would like to use it for some numerical experiments and prefers visit for output.

**Comment by samuelpmishLLNL** [comment]
> Any other issues with this branch? @solberg2 would like to use it for some numerical experiments and prefers visit for output.

Sorry I didn't even know about this PR! I'll take a look through now.

**Comment by jamiebramwell** [comment]
ping @jeromesolberg . This is the branch you should use.

**Review by samuelpmishLLNL — APPROVED** [review]

**Pull request merged**
