### PR TITLE
Bugfix/white238/turnoffdocs

### PR DESCRIPTION
**Pull request by white238**
LC's Sphinx and Doxygen keep failing with random incompatibilities.  This turns off docs for the build scripts until we rebuild a new set of Devtools with our own Sphinx/Doxygen.

### CODE REVIEW

**Comment by white238** [comment]
LGTM

**Review by jamiebramwell — APPROVED** [review]

**Review by joshessman-llnl — APPROVED** [review]
We may also be able to turn off the generation of the PDF doxygen documentation and do just the HTML

**Comment by white238** [comment]
> We may also be able to turn off the generation of the PDF doxygen documentation and do just the HTML

Yea.  I think i would prefer to have a working doxygen though.  If this doesn't work or proves more annoying, we can go down that route.

**Comment by white238** [comment]
LGTM

**Pull request merged**
