### PR TITLE
Clarify error, update to new host-config

### PR DESCRIPTION
**Pull request by white238**
for you @jamiebramwell

### CODE REVIEW

**Comment by joshessman-llnl** [comment]
LGTM

**Comment by joshessman-llnl** [comment]
Need to add -Xcompiler to https://github.com/LLNL/serac/blob/25543039445dca85d1f62c1997c94bc819c82493/scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/compilers.yaml#L11-L12

**Comment by white238** [comment]
> Need to add -Xcompiler to
> 
> https://github.com/LLNL/serac/blob/25543039445dca85d1f62c1997c94bc819c82493/scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/compilers.yaml#L11-L12

can't add it there because it would end up on the regular compile line..

**Comment by joshessman-llnl** [comment]
https://github.com/LLNL/serac/blob/develop/scripts/uberenv/packages/serac/package.py#L279

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
IT PASSED!!! I'M FREE!!!

**Review by jamiebramwell — APPROVED** [review]

**Comment by white238** [comment]
I need a "Hide your shameful amount of LGTMs" button

**Review by joshessman-llnl — APPROVED** [review]

**Pull request merged**
