### PR TITLE
Enable docker container TPL builds and azure pipelines

### PR DESCRIPTION
**Pull request by jamiebramwell**
This enables a docker image build with gcc-8. The built container is located [here](https://hub.docker.com/repository/docker/seracllnl/tpls).

### CODE REVIEW

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
@adrienbernede , I hope I didn't squish the gitlab stuff! Let me know if you see anything suspicious.

**Comment by adrienbernede** [comment]
> @adrienbernede , I hope I didn't squish the gitlab stuff! Let me know if you see anything suspicious.

The pipeline failed at allocation time in the first "LGTM" comment, I relaunched it, and pushed a fix for allocation job improvement.

The second LGTM comment hasn’t triggered any pipeline apparently, I’ll investigate that.

**Pull request merged**
