### PR TITLE
Deleting some leftover unused shared_ptrs

### PR DESCRIPTION
**Pull request by jamiebramwell**
I believe these `shared_ptr`s are leftovers from the refactoring work.

### CODE REVIEW

**Comment by jamiebramwell** [comment]
LGTM

**Review by joshessman-llnl — APPROVED** [review]
Good catch, I wonder if any static analysis tools would have caught something like this

**Comment by jamiebramwell** [comment]
> 
> 
> Good catch, I wonder if any static analysis tools would have caught something like this

I only noticed while resolving conflicts on my contact branch! It would be nice to have a static analysis thing look for stuff like this.

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
@samuelpmishLLNL , could you take a look at this? Thanks!

**Review by samuelpmishLLNL — APPROVED** [review]

**Comment by jamiebramwell** [comment]
LGTM

**Comment by samuelpmishLLNL** [comment]
> 
> 
> Good catch, I wonder if any static analysis tools would have caught something like this

interesting that compilers will warn on unused basic types, but not on `std::shared_ptr`: https://godbolt.org/z/MW9xzn

**Comment by jamiebramwell** [comment]
> 
> 
> > Good catch, I wonder if any static analysis tools would have caught something like this
> 
> interesting that compilers will warn on unused basic types, but not on `std::shared_ptr`: https://godbolt.org/z/MW9xzn

It might be due to the fact that uninitialized pointers (i.e. `nullptr`s) are a common design requirement.

**Comment by samuelpmishLLNL** [comment]
Uninitialized is different than never used, though! I guess any type with a default constructor might actually be doing something in the background, so "unused" doesn't necessarily imply "does nothing". TIL

**Pull request merged**
