### PR TITLE
Add new quartz host-configs

### PR DESCRIPTION
**Pull request by white238**
Still trying to test these host-configs...

### CODE REVIEW

**Comment by white238** [comment]
serac_dynamic_solver and serac_linelastic_solver fail on all three host-configs

**Comment by white238** [comment]
serac_dynamic_solver:

/usr/WS2/white238/serac/repo/tests/serac_linelastic_solver.cpp:98: Failure
The difference between 0.128065 and x_norm is 0.12806500000000001, which exceeds 0.00001, where
0.128065 evaluates to 0.12806500000000001,
x_norm evaluates to 0, and
0.00001 evaluates to 1.0000000000000001e-05.
/usr/WS2/white238/serac/repo/tests/serac_linelastic_solver.cpp:98: Failure
The difference between 0.128065 and x_norm is 0.12806500000000001, which exceeds 0.00001, where
0.128065 evaluates to 0.12806500000000001,
x_norm evaluates to 0, and
0.00001 evaluates to 1.0000000000000001e-05.
/usr/WS2/white238/serac/repo/tests/serac_linelastic_solver.cpp:98: Failure
The difference between 0.128065 and x_norm is 0.12806500000000001, which exceeds 0.00001, where
0.128065 evaluates to 0.12806500000000001,
x_norm evaluates to 0, and
0.00001 evaluates to 1.0000000000000001e-05.

**Comment by jamiebramwell** [comment]
> 
> 
> serac_dynamic_solver and serac_linelastic_solver fail on all three host-configs

This is expected. I'm looking at this today and will hopefully have a PR addressing this soon.

**Comment by white238** [comment]
Lets approve this then.

**Comment by adrienbernede** [comment]
@white238 
What’s the difference (in usage, purpose on whatever) between these host-config files and those generated by Uberenv?

**Comment by adrienbernede** [comment]
I see you are nearby :)

**Comment by white238** [comment]
> @white238
> What’s the difference (in usage, purpose or whatever) between these host-config files and those generated by Uberenv?

These are the host-configs generated by Uberenv but point to an installed version in a shared location.  This allows developers to use them and not have to rebuild them locally themselves.

**Comment by adrienbernede** [comment]
OK, thanks.
If you think we should periodically build with these, lemme know!

**Comment by white238** [comment]
> OK, thanks.
> If you think we should periodically build with these, lemme know!

I typically like to have two levels of testing:

1) Nightly full builds which include TPLs and the projects source and tests
2) Nightly and on each PR just testing against the host-configs that are checked in

For Serac, it is not too bad to build the TPLs each time (due to the fact here is only like 4 and the TPLs take 5 minutes or so) but eventually building all the TPLs will become too much for every PR.  We can revisit this at a later date.

**Comment by adrienbernede** [comment]
That’s typically what I envisioned :)

**Pull request merged**
