### PR TITLE
Update MFEM to 4.7

### PR DESCRIPTION
**Pull request by chapman39**
* update mfem
* undo this bugfix pr https://github.com/LLNL/serac/pull/1111 as it's no longer needed

### CODE REVIEW

**Review by white238 — APPROVED** [review]

**Comment by white238** [comment]
@samuelpmishLLNL can you confirm this works with your ubuntu cuda build? It includes the amgx link order issue in MFEM

**Comment by samuelpmishLLNL** [comment]
> @samuelpmishLLNL can you confirm this works with your ubuntu cuda build? It includes the amgx link order issue in MFEM

It looks like the TPLs build with CUDA support, but serac's build has some errors when using clang as a host compiler
```
error: unrecognized command-line option ‘-fopenmp=libomp’; did you mean ‘-fopenmp-simd’?
```

Also, you still have access to that ubuntu machine for testing in the future. @chapman39 do you want an account on an Ubuntu 22.04 + CUDA machine too?

**Review by samuelpmishLLNL — APPROVED** [review]

**Comment by white238** [comment]
> > @samuelpmishLLNL can you confirm this works with your ubuntu cuda build? It includes the amgx link order issue in MFEM
> 
> It looks like the TPLs build with CUDA support, but serac's build has some errors when using clang as a host compiler
> 
> ```
> error: unrecognized command-line option ‘-fopenmp=libomp’; did you mean ‘-fopenmp-simd’?
> ```
> 
> Also, you still have access to that ubuntu machine for testing in the future. @chapman39 do you want an account on an Ubuntu 22.04 + CUDA machine too?

Can you send me an email with the concretization? clang is tested in multiple places so I am pretty sure something went wrong with spack.

**Comment by chapman39** [comment]
> Also, you still have access to that ubuntu machine for testing in the future. @chapman39 do you want an account on an Ubuntu 22.04 + CUDA machine too?

@samuelpmishLLNL Yeah. Is the machine at a shared office location, or?

**Pull request merged**
