### PR TITLE
Change default output and reorient tet mesh

### PR DESCRIPTION
**Pull request by jamiebramwell**
This changes the default output type to GLVis which does not require initialization. It also reorients the tet-based ball mesh for use with high order H curl elements.

### CODE REVIEW

**Comment by jamiebramwell** [comment]
LGTM

**Review by jonwong12 — APPROVED** [review]
It looks fine to me. It would be nice in serac if we could return a warning if the "root_name" already is being used. I'm not sure if there is some mechanism to check this already in mfem.

**Review by joshessman-llnl — APPROVED** [review]

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
LGTM

**Pull request merged**
