### PR TITLE
Change the default finite element state to be scalar-valued

### PR DESCRIPTION
**Pull request by jamiebramwell**
This changes our default finite element state to be scalar valued. This is more in line with MFEM and other finite element libraries.

### CODE REVIEW

**Comment by jamiebramwell** [comment]
LGTM

**Review by joshessman-llnl — APPROVED** [review]

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
@jonwong12 @samuelpmishLLNL could you take a look at this?

**Comment by jamiebramwell** [comment]
LGTM

**Comment by jamiebramwell** [comment]
LGTM

**Comment by joshessman-llnl** [comment]
LGTM

**Review by samuelpmishLLNL — APPROVED** [review]

**Pull request merged**
