### PR TITLE
Restart and baseline option

### LINKED ISSUE #655: Add restart integration tests
Add a new optional parameter in `tolerance_test` to handle restart tests.

Something like this:

```
tolerance_test(name="dyn_exp_solve_serial",
    input_file="some_input.lua",
    restart_cycle="10")
```

Then the test workflow would be this:

```
serac -i some_input.lua  // this runs fully
serac -i some_input --restart-cycle=10  // restarts previous run on cycle 10
// run tolerance_test.py against last summary file and baseline
```

If the restart_cycle parameter is not given it should not run the second serac command like it is currently.

### PR DESCRIPTION
**Pull request by chapman39**
fixes #655

### CODE REVIEW

**Comment by chapman39** [comment]
postponed till https://github.com/LLNL/serac/issues/672 is fixed

**Comment by chapman39** [comment]
ready for review. documentation still needed but can be done in a future pr.

connects with https://github.com/LLNL/serac_tests/pull/11

**Comment by chapman39** [comment]
had to add `--sleepBeforeSrun=2` since 1 sometimes didn't pass all tolerance tests.

**Comment by jamiebramwell** [comment]
> had to add `--sleepBeforeSrun=2` since 1 sometimes didn't pass all tolerance tests.

Why was this failing? Was it hanging due to weird slurm behavior?

**Comment by chapman39** [comment]
> > had to add `--sleepBeforeSrun=2` since 1 sometimes didn't pass all tolerance tests.
> 
> Why was this failing? Was it hanging due to weird slurm behavior?

It was failing because of ATS. Sometimes a tolerance test will run before serac is finished generating the summary file. It works fine now - it's just slightly slower.

**Review by white238 — APPROVED** [review]
Approved pending docs in test PR.  Thanks @chapman39 !

**Review by jamiebramwell — APPROVED** [review]

**Pull request merged**
