### PR TITLE
Fix the nonlinear thermal reaction test

### LINKED ISSUE #654: static_reaction_exact.lua times out on serac test
error message:

> ERROR (/usr/WS2/meemee/serac/repo/src/serac/infrastructure/input.cpp:332)]
> Coefficient definition does not contain known type.
> 
> Frame 1: axom::slic::logErrorMessage(std::string const&, std::string const&, int)
> Frame 2: FromInlet<serac::input::CoefficientInputOptions>::operator()(axom::inlet::Container const&)
> Frame 4: FromInlet<serac::input::BoundaryConditionInputOptions>::operator()(axom::inlet::Container const&)
> Frame 6: std::unordered_map<std::string, serac::input::BoundaryConditionInputOptions, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, serac::input::BoundaryConditionInputOptions> > > axom::inlet::Container::getCollection<std::string, serac::input::BoundaryConditionInputOptions>() const
> Frame 9: FromInlet<serac::ThermalConduction::InputOptions>::operator()(axom::inlet::Container const&)
> Frame 14: ../../build-quartz-toss_3_x86_64_ib-clang@10.0.0-debug/bin/serac() [0x769189]

### PR DESCRIPTION
**Pull request by jamiebramwell**
This fixes the nonlinear reaction input file and re-enables the related test.

Resolves https://github.com/LLNL/serac/issues/654

### CODE REVIEW

**Comment by white238** [comment]
Should this be added to the integration tests as well?

**Comment by chapman39** [comment]
> Should this be added to the integration tests as well?

once it's in develop i can re-add the `.ats` file for it.

**Comment by jamiebramwell** [comment]
> > Should this be added to the integration tests as well?
> 
> once it's in develop i can re-add the `.ats` file for it.

I already did! I needed to figure out how to do that anyway 😆 https://github.com/LLNL/serac_tests/pull/6

**Comment by jamiebramwell** [comment]
@chapman39 @white238 any other issues in this PR?

**Review by chapman39 — APPROVED** [review]

**Review by white238 — APPROVED** [review]

**Comment by white238** [comment]
Sorry thought i actually approved this already.

**Pull request merged**
