### PR TITLE
add differentiable eigenvalue calculation for small matrices

### PR DESCRIPTION
**Pull request by samuelpmishLLNL**

### CODE REVIEW

**Review by kswartz92 — APPROVED** [review]
I've been successfully using this functionality in LiDO. I believe @samuelpmishLLNL mentioned this wouldn't work on GPUs, but in the meantime it's very useful for computing maximum principal stress.

**Comment by samuelpmishLLNL** [comment]
lgtm

**Review by jamiebramwell — APPROVED** [review]
This will be super useful! Thanks @samuelpmishLLNL !

**Comment by samuelpmishLLNL** [comment]
@jamiebramwell 
thanks for doing the `make style` for me, I don't have a machine with the right version of clang-format any more, and apparently clang-format-11 gives slightly different results

**Comment by jamiebramwell** [comment]
> @jamiebramwell thanks for doing the `make style` for me, I don't have a machine with the right version of clang-format any more, and apparently clang-format-11 gives slightly different results

Yeah, the style thing is annoying. We should probably just do a batch clang update on all of our platforms.

**Pull request merged**
