### PR TITLE
Remove the physics/utilities directory

### PR DESCRIPTION
**Pull request by jamiebramwell**
The removes the generic `src/physics/utilities` directory in favor of more logical locations. In particular:

- It moves `functional` to `serac/numerics`.
- It moves all state related objects to `serac/physics/state`.
- It moves all boundary condition information to `serac/physics/boundary_conditions`.

It is probably easier to check out this branch than to review it over the web. Suggestions and improvements welcome!

### CODE REVIEW

**Comment by samuelpmishLLNL** [comment]
I think this is an improvement, but there are still a few changes that might be worth making while we're rearranging things:

1. the directory `serac/physics/operators` isn't really related to the physics, maybe move it to `serac/numerics/operators` (?)
2. the test `serac/physics/tests/serac_boundary_cond.cpp` might make more sense in `serac/physics/boundary_conditions/tests/`.
3. the mesh-related sourcefiles in `serac/numerics` feel out of place to me, but I don't see an obvious better place to put them (maybe `serac/infrastructure`, but I don't feel great about that).
4. the nearly-root directory `serac/coefficients` makes it seem like it's contents are a fundamental pillar of serac, but the associated files are used rarely, if at all (I see exactly 1 use of `{Shear,Bulk}SensitivityCoefficient`, and 0 uses of `{initial,reference}Configuration()`). Moving the directory to `serac/physics/coefficients` would put them closer to their point of use.

And, we've got a handful of things living in the `mfem_ext` namespace scattered around the repository. Is this `mfem_ext` namespace for things we intend to upstream to mfem, or just serac-only things that derive from mfem? If that namespace is only for things intended to be upstreamed to mfem, it might make sense to put those objects in a separate directory (e.g. `serac/mfem_ext`). Also: there was some discussion in previous meetings about putting `Functional` in the `mfem_ext` namespace.

**Comment by jamiebramwell** [comment]
> 
> 
> I think this is an improvement, but there are still a few changes that might be worth making while we're rearranging things:
> 
>     1. the directory `serac/physics/operators` isn't really related to the physics, maybe move it to `serac/numerics/operators` (?)
> 
>     2. the test `serac/physics/tests/serac_boundary_cond.cpp` might make more sense in `serac/physics/boundary_conditions/tests/`.
> 
>     3. the mesh-related sourcefiles in `serac/numerics` feel out of place to me, but I don't see an obvious better place to put them (maybe `serac/infrastructure`, but I don't feel great about that).
> 
>     4. the nearly-root directory `serac/coefficients` makes it seem like it's contents are a fundamental pillar of serac, but the associated files are used rarely, if at all (I see exactly 1 use of `{Shear,Bulk}SensitivityCoefficient`, and 0 uses of `{initial,reference}Configuration()`). Moving the directory to `serac/physics/coefficients` would put them closer to their point of use.
> 
> 
> And, we've got a handful of things living in the `mfem_ext` namespace scattered around the repository. Is this `mfem_ext` namespace for things we intend to upstream to mfem, or just serac-only things that derive from mfem? If that namespace is only for things intended to be upstreamed to mfem, it might make sense to put those objects in a separate directory (e.g. `serac/mfem_ext`). Also: there was some discussion in previous meetings about putting `Functional` in the `mfem_ext` namespace.

1. ✔️ 
2. ✔️ 
3. Maybe `serac/mesh`? `serac/infrastructure` could also work, but that's more CS stuff.
4. I like `serac/physics/coefficients` because they're generally tied to a specific physics.

**Comment by white238** [comment]
> 
> 
> > I think this is an improvement, but there are still a few changes that might be worth making while we're rearranging things:
> > ```
> > 1. the directory `serac/physics/operators` isn't really related to the physics, maybe move it to `serac/numerics/operators` (?)
> > 
> > 2. the test `serac/physics/tests/serac_boundary_cond.cpp` might make more sense in `serac/physics/boundary_conditions/tests/`.
> > 
> > 3. the mesh-related sourcefiles in `serac/numerics` feel out of place to me, but I don't see an obvious better place to put them (maybe `serac/infrastructure`, but I don't feel great about that).
> > 
> > 4. the nearly-root directory `serac/coefficients` makes it seem like it's contents are a fundamental pillar of serac, but the associated files are used rarely, if at all (I see exactly 1 use of `{Shear,Bulk}SensitivityCoefficient`, and 0 uses of `{initial,reference}Configuration()`). Moving the directory to `serac/physics/coefficients` would put them closer to their point of use.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And, we've got a handful of things living in the `mfem_ext` namespace scattered around the repository. Is this `mfem_ext` namespace for things we intend to upstream to mfem, or just serac-only things that derive from mfem? If that namespace is only for things intended to be upstreamed to mfem, it might make sense to put those objects in a separate directory (e.g. `serac/mfem_ext`). Also: there was some discussion in previous meetings about putting `Functional` in the `mfem_ext` namespace.
> 
>     1. ✔️
> 
>     2. ✔️
> 
>     3. Maybe `serac/mesh`? `serac/infrastructure` could also work, but that's more CS stuff.
> 
>     4. I like `serac/physics/coefficients` because they're generally tied to a specific physics.

3) I'd prefer `serac/mesh`

**Comment by jamiebramwell** [comment]
The only thing left is the `mfem_ext` namespace issue. This unfortunately hasn't been as useful as I hoped. Should we just git rid of it? If we want to keep it, should we move them into a separate directory (maybe `serac/mfem_ext`)? Thoughts?

**Comment by white238** [comment]
> 
> 
> The only thing left is the `mfem_ext` namespace issue. This unfortunately hasn't been as useful as I hoped. Should we just git rid of it? If we want to keep it, should we move them into a separate directory (maybe `serac/mfem_ext`)? Thoughts?

I'd leave that for a separate PR/discussion.

**Comment by white238** [comment]
Should `serac_functional` depend on `serac_physics`? That seems circular and problematic going forward.

https://github.com/LLNL/serac/blob/4e5a33d6bdb34794ced6107d820e7fc55bc2822e/src/serac/numerics/functional/CMakeLists.txt#L7

I only see this:

https://github.com/LLNL/serac/blob/4e5a33d6bdb34794ced6107d820e7fc55bc2822e/src/serac/numerics/functional/boundary_integral.hpp#L18

but I don't see anything actually being used from this header.

It seems like the only thing that it should depend on is `serac_numerics` and `serac_infrastructure`.

**Comment by white238** [comment]
Should `physics/state` be pulled to the top level since it doesn't depend on anything in `physics` only `infrastructure`?

The same question could be asked for `physics/materials`

**Comment by samuelpmishLLNL** [comment]
> Should serac_functional depend on serac_physics? That seems circular and problematic going forward.

I don't think `Functional` needs anything from `serac_physics`.

> Should `physics/state` be pulled to the top level since it doesn't depend on anything in `physics` only `infrastructure`?
> 
> The same question could be asked for `physics/materials`

I'd vote to keep `serac/physics/state` where it is, because the stuff in `serac/physics` depends on it

**Comment by jamiebramwell** [comment]
> 
> 
> > Should serac_functional depend on serac_physics? That seems circular and problematic going forward.
> 
> I don't think `Functional` needs anything from `serac_physics`.
> 
> > Should `physics/state` be pulled to the top level since it doesn't depend on anything in `physics` only `infrastructure`?
> > The same question could be asked for `physics/materials`
> 
> I'd vote to keep `serac/physics/state` where it is, because the stuff in `serac/physics` depends on it

I agree with @samuelpmishLLNL . The `state` and `materials` concepts are closely tied to specific physics, while `numerics` is more pure mathematical abstractions.

**Comment by jamiebramwell** [comment]
I think I've worked in all the comments. Any other thoughts?

**Review by white238 — APPROVED** [review]

**Review by samuelpmishLLNL — APPROVED** [review]

**Review by joshessman-llnl — APPROVED** [review]

**Pull request merged**
