### PR TITLE
CUDA Azure Bugfix: Only convert CTest output to JUnit if testing is enabled

### LINKED ISSUE #1262: Conversion to JUnit should not be running in CUDA Azure pipelines
The CUDA Azure pipeline doesn't run tests due to no GPU's on the runner. This conversion needs to be skipped to silence this warning.

```
[Checking to see if xsltproc exists...]
[exe: xsltproc --version]
[Converting CTest XML to JUnit XML]
[exe: xsltproc -o /home/serac/serac/_serac_build_and_test_2024_11_05_15_14_03/build-gcc@12.3.0_cuda/junit.xml cmake/blt/tests/ctest-to-junit.xsl /home/serac/serac/_serac_build_and_test_2024_11_05_15_14_03/build-gcc@12.3.0_cuda/Testing/*/Test.xml]
[ERROR: [return code: 6] from command: xsltproc -o /home/serac/serac/_serac_build_and_test_2024_11_05_15_14_03/build-gcc@12.3.0_cuda/junit.xml cmake/blt/tests/ctest-to-junit.xsl /home/serac/serac/_serac_build_and_test_2024_11_05_15_14_03/build-gcc@12.3.0_cuda/Testing/*/Test.xml]
[WARNING: Converting to JUnit failed.]
```

### PR DESCRIPTION
**Pull request by chapman39**
Fixes #1262

### CODE REVIEW

**Review by white238 — APPROVED** [review]
Thanks for the quick turn around @chapman39 !

**Comment by white238** [comment]
Well it got rid of the error after the build... but the warning is still there under the test section and on the main page. =/

**Comment by white238** [comment]
We could drop an empty/fake Text.xml file to shut it up when tests aren't being run...  or play around with some options here to see if it quiets it:

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2?view=azure-pipelines&tabs=trx%2Ctrxattachments%2Cyaml

**Comment by chapman39** [comment]
Putting on draft for now till I resolve the remaining warning.

Also kind of funny we just barely have enough space for the cuda builds

Screenshot 2024-11-05 at 6 01 31 PM

**Review by white238 — APPROVED** [review]

**Review by tupek2 — APPROVED** [review]

**Pull request merged**
