### PR TITLE
Doxygen-ing enumerations

### PR DESCRIPTION
**Pull request by jonwong12**
Documenting enumerations adds links to show which file the enum is defined in. It also so allows enum values to be searchable.

This is especially useful when you just want to add "one more enum option".

Feel free to make description code suggestions!

### CODE REVIEW

**Comment by white238** [comment]
Link to at least one change.

https://serac.readthedocs.io/en/bugfix-jonwong12-doxygen_enums/doxygen/html/namespaceserac.html#ad164a9ca29bad0a5b5ca812c3dab35c8

**Review by white238 — APPROVED** [review]
Thanks @jonwong12

**Review by jamiebramwell — APPROVED** [review]
Awesome! Thanks for doing this!

**Comment by jamiebramwell** [comment]
LGTM

**Pull request merged**
