### PR TITLE
Update BLT

### PR DESCRIPTION
**Pull request by chapman39**

### CODE REVIEW

**Comment by chapman39** [comment]
This was the test_newton error i was getting

```
[ERROR in line 577 of file /usr/WS2/meemee/serac/repo/src/serac/infrastructure/../../serac/numerics/functional/tuple_tensor_dual_functions.hpp]
MESSAGE=solve_scalar_equation: root not bracketed by input bounds.
** StackTrace of 16 frames **
Frame 1: axom::slic::logErrorMessage(std::string const&, std::string const&, int)
Frame 2: ./tests/test_newton() [0x48f1c2]
Frame 3: ScalarEquationSolver_AbortsIfRootNotBracketedByCaller_Test::TestBody()
Frame 4: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
Frame 5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
Frame 6: testing::Test::Run()
Frame 7: testing::TestInfo::Run()
Frame 8: testing::TestSuite::Run()
Frame 9: testing::internal::UnitTestImpl::RunAllTests()
Frame 10: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
Frame 11: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
Frame 12: testing::UnitTest::Run()
Frame 13: RUN_ALL_TESTS()
Frame 14: main
Frame 15: __libc_start_main
Frame 16: ./tests/test_newton() [0x48cd17]
=====


***********************************
/usr/WS2/meemee/serac/repo/src/serac/numerics/functional/tests/test_newton.cpp:56: Failure
Death test: { [[maybe_unused]] auto result = solve_scalar_equation([](auto x) { return x * x - 2.0; }, x0, lower, upper, default_solver_options); }
    Result: died but not with expected error.
  Expected: contains regular expression "solve_scalar_equation: root not bracketed by input bounds."
Actual msg:
```

**Comment by chapman39** [comment]
Changing the expected error output to an empty string fixes the issue but I'm not sure if thats the best solution.

**Comment by chapman39** [comment]
@jamiebramwell @white238 do you think we should just remove this death test? (since it was likely not even being tested before).

**Comment by jamiebramwell** [comment]
We have other tests that check for an exception. It's probably a good idea to do that instead. For example: https://github.com/LLNL/serac/blob/e2ae10bbd3ecb855bf21b72ac7aa6eb4a77a3a1d/src/serac/infrastructure/tests/error_handling.cpp#L24

**Comment by jamiebramwell** [comment]
That said, I defer to @white238 on this one.

**Comment by chapman39** [comment]
Should pass now

**Review by samuelpmishLLNL — APPROVED** [review]

**Review by jamiebramwell — APPROVED** [review]

**Review by white238 — APPROVED** [review]

**Pull request merged**
